---
- hosts: webservers
  tasks:
   - name: Install forever
     npm: name=forever global=yes state=present

   #- name: perform  cloning git
     #command: git clone https://github.com/Thirupathichalla-arch/SonarQubeNodeJS.git ~/SonarQubeNodeJS

   - name: npm installation
     command: npm install
     args:
       chdir: ~/SonarQubeNodeJS

   - name: execute npm
     command: forever start SonarQubeNodeJS/app/views/index.html
