---
- hosts: webservers
  tasks:
   - name: Install forever
     npm: name=forever global=yes state=present

   - name: npm installation
     args:
       chdir: /SonarQubeNodeJS
     command: npm install

   - name: execute npm
     command: forever start SonarQubeNodeJS/app/views/index.html
